#!/usr/bin/env bash
# Configures domain zone so that subdomain www points to load balancer

answers () {
    do_dig=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $do_dig" | awk '{ print "The subdomain " $1 " is a " $2 " record and points to " $3 }'
}
   
if [ "$#" == 1 ]
  then
      answers "$1" "www"
      answers "$1" "lb-01"
      answers "$1" "web-01"
      answers "$1" "web-02"
  else
      answers "$1" "$2"
fi