#!/usr/bin/env bash
#Configures nginx to redirect to another
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html
printf %s "server {
        listen 80;
        listen [::]:80;

        server_name example.com;

        root /etc/nginx/html;
        index index.html;

        location / {
               return 301 https://www.youtube.com/watch?v=M68i7ray2Qo;
        }
}" > /etc/nginx/sites-available/default

sudo service nginx restart