#!/usr/bin/env bash
#Configures nginx to redirect to another
sudo apt-get -y update;
sudo apt-get -y install nginx;

mkdir /etc/nginx/html;
touch /etc/nginx/html/index.html
echo "Hello World" | sudo tee /index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html
printf %s "server {
        listen 80;
        listen [::]:80;

        server_name example.com;

        root /etc/nginx/html;
        index index.html;

        location /redirect_me {
               return 301 https://www.youtube.com/watch?v=M68i7ray2Qo;
        }

        error_page 404 /404.html;
        location /404 {
                root /etc/nginx/html;
                internal;
        }
}" > /etc/nginx/sites-available/default

sudo service nginx restart