#!/usr/bin/env bash
# Install nginx 
#+ Configures /redirect_me as "301 Moved Permanently"
#+ Includes custom 404 page
#+ Custom HTTP header named X-Served-By

sudo apt-get -y update;
sudo apt-get -y install nginx;

mkdir /etc/nginx/html;
touch /etc/nginx/html/index.html
echo "Hello World" | sudo tee /index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html
printf %s "server {
        listen 80;
        listen [::]:80;
        add_header X-Served-By $HOSTNAME;

        root /etc/nginx/html;
        index index.html;

        location /redirect_me {
               return 301 https://www.youtube.com/watch?v=M68i7ray2Qo;
        }

        error_page 404 /404.html;
        location /404 {
                root /etc/nginx/html;
                internal;
        }
}" > /etc/nginx/sites-available/default

sudo service nginx restart