#!/usr/bin/env bash
#This script is for displaying Best School 10 times but Hi for the 9th iteration

i=1
j=9
while [ $i -le 10 ];
do
	echo "Best School"
	if [ "$i" = "$j" ]; then
		echo "Hi"
	fi
	((i++))
done
