#!/usr/bin/env bash
#This script loops from 1 to 10 and displays "bad luck" for the 4th iteration "good luck" for the 8th iteration and "Best School" for the others

i=1
j=4
k=8

while [ $i -le 10 ]
do
	if [ "$i" = "$j" ]; then
		echo "bad luck"
	elif [ "$i" = "$k" ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
