#!/usr/bin/env bash
#This script displays numbers 1 to 20 and displays 4 and bad luck from China for the 4th iteration, displays 9 and bad luck from Japan displays 17 and bad luck from Italy

i=1

while [ $i -le 20 ];
do
	case $i in
	"4")
		echo "$i"
		echo "bad luck from China"
		;;
	"9")
		echo "$i"
		echo "bad luck from Japan"
		;;
	"17")
		echo "$i"
		echo "bad luck from Italy"
		;;
	*)
		echo "$i"
		;;
	esac
	((i++))
done
