#!/usr/bin/env bash
# This script is for displaying
# The content of the current directory
# In a list format
#Where only the part of the name after the fist dash is displayed

DIR="$(ls)"
for i in $DIR;
do
	echo "$i" | cut -d "-" -f2
done
