#!/usr//bin/env bash
# This script configures an Ubuntu server with below requirments
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo -e "\n8.8.8.8\tfacebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
