#!/usr/bin/env bash
#Configures nginx to redirect to another

server {
        listen 80;
        listen [::]:80;

        server_name 3.89.29.78;

        add_header X-Served-By 4268-web-01
      
        location /airbnb-onepage/ {
               proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
        }

        #404 error page
        error_page 404 /404.html;
        location /404 {
            root /var/www/html;
            internal;
        }
}